#+TITLE:Forecast Health Australia
#+AUTHOR:Forecast Health Australia PTY LTD
#+OPTIONS: num:nil
#+SETUPFILE:/home/rory/Documents/org-html-themes/org/theme-readtheorg-local.setup

* Aims
We aim to increase understanding about priority-setting in healthcare.
We achieve this in the following ways:
1) Building models
2) Sharing our work
3) Reviewing other models

* Sharing our work
You can find our GitHub code repository at [[https://github.com/ForecastHealth][github.com/ForecastHealth]].
Our codebase is currently private, but check back for regular updates.

* Reviewing other models
We are always interested to review your, or other groups' models.
Our general approach to this is follows:
- review the original model with the original assumptions
- review the original model with modified assumptions
- review the re-written* model with original assumptions
- review the re-written* model with modified assumptions

/*We re-write the model using our codebase and engine/

* Contact
If we can help you with any of our aims, please get in contact with us at [[mailto:info@forecasthealth.org][info@forecasthealth.org]]

* About
Forecast Health Australia PTY LTD (ACN: 658 291 653) is an Australian Proprietary Company, Limted By Shares.

The Director and Owner of Forecast Health Australia is Rory Watts, PhD, MPH.
You can find more information about him [[https://rorywatts.github.io/][here.]]
