#+TITLE:Forecast Health Australia
#+AUTHOR:Forecast Health Australia PTY LTD
#+OPTIONS: num:nil
#+SETUPFILE:/home/rory/Documents/org-html-themes/org/theme-readtheorg-local.setup

* Aims
Forecast Health Australia aims to increase decision-making capacity in health.
We make models and tools to help health, economic and financing decisions.
We work globally, and do the following things:
1) Create modelling tools
2) Help you build models
3) Review the models and tools of others

* Our Tools
You can find our GitHub code repository at [[https://github.com/ForecastHealth][github.com/ForecastHealth]].
Our codebase is currently private, but check back for regular updates.

* Reviewing other models
We are always interested to review your, or other groups' models.
Our general approach to this is follows:
- review the original model with the original assumptions
- review the original model with modified assumptions
- review the re-written* model with original assumptions
- review the re-written* model with modified assumptions

/*We re-write the model using our own tools/

* Contact
If we can help you with any of our aims, please get in contact with us at [[mailto:info@forecasthealth.org][info@forecasthealth.org]]

* About
Forecast Health Australia PTY LTD (ACN: 658 291 653) is an Australian Proprietary Company, Limted By Shares.

The Director and Owner of Forecast Health Australia is Rory Watts, PhD, MPH.
You can find more information about him [[https://rorywatts.github.io/][here.]]
